@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.cccstudio.enchantmentFantasy.enchantment.weapon;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;