@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.cccstudio.enchantmentFantasy.enchantment;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;